"""empty message

Revision ID: f46102effa36
Revises: f27b627d8352
Create Date: 2020-07-07 08:36:17.137316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46102effa36'
down_revision = 'f27b627d8352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'rating')
    # ### end Alembic commands ###
